### ISSUE TITLE
Penta crashes when circle/star receives gate

### ISSUE THREAD

**Issue by Cubistguitar** [codygeary/CVfunk-Modules#11] opened 2024-04-16 23:59 UTC
Hi Cody,
I just started experimenting with Penta, a fun design. I cannot seem to send a gate to the circle star input without instant crash. 
I have tried a divided output from Clocked and a VCV PUSH gate. always crash.

I run VCV PRO standalone 2.4.1 Windows 10

[log.txt](https://github.com/codygeary/CVfunk-Modules/files/15003887/log.txt)

**Comment by codygeary** [comment] 2024-04-17 08:09
Thank you for the report Cubistguitar!

Can you please give version 2.0.3 a try and see if it fixes the problem on your platform (currently in the queue for update in the library). You can find the build on the right side in Git. There was a potential issue with a null pointer on the star-circle mapping function that I fixed in 2.0.2->2.0.3. Hopefully, if that was the cause, then it's already patched.

If that doesn't fix it, I'll try some other things.

**Comment by codygeary** [comment] 2024-04-17 09:54
Oh I see. Okay, I'm looking into it, there's a second dynamic pointer that might also be a problem for windows10.

**Comment by deadlydeer39** [comment] 2024-04-17 10:10
yes ! great for me it's working 
thx so much ! you have a great collection !

**Comment by codygeary** [comment] 2024-04-17 10:19
Awesome! Thanks for your help with the testing. Enjoy!

**Closed** 2024-04-18 10:21 UTC
