### ISSUE TITLE
MetaModule: Penta Sequencer not triggering

### ISSUE THREAD

**Issue by rjsmith** [codygeary/CVfunk-Modules#27] opened 2024-11-24 13:53 UTC
Penta Sequencer on the MetaModule is not triggering to advance the sequencer steps.  

Steps to reproduce:

1. Run the patch attached here on a MetaModule:
[CV Funk PentaSeqOuros Test.zip](https://github.com/user-attachments/files/17893507/CV.Funk.PentaSeqOuros.Test.zip)

2. connect a gate into the MM Gate In 1 (I used a gate sequence from running Pams Pro Workout). 

3. Connect audio outs from the MM outs 1 & 2 to eurorack audio interface etc

5. Also connect MM out 5 (internally patched to the Penta Sequencer A output) to a scope

6. Observe no pitch change.   Also observe no CV change from the patched "A" output. 

Also use the mapped knobset to manually change the "A" output level using the current mapped step knob - observe on the scope that the output seems to track rate of change of knob (either positive = clockwise, or negative =- anticlockwise) but then it quickly returns to 0V. 

<img width="874" alt="image" src="https://github.com/user-attachments/assets/2a6dae23-58f7-484f-8ebe-384653f7ee51">

MM firmware v1.4.6

CV Funk repo commit: 2ecf238ebe3a80b9507e9065c5feea8494cca26c
Compiled using ARM GCC toolchain 12.3 on MacOS 14.6.1

**Comment by codygeary** [comment] 2024-11-24 17:52
Are you using this build of the MM:
https://github.com/4ms/CVfunk-Modules

Can you please also post this in that Git. I don't personally have a Meta yet, so I can't try to reproduce the bug and see what is causing it. It seems like very weird module behavior to me though.

**Comment by rjsmith** [comment] 2024-11-24 19:43
Yes, using the 4ms fork. Happy to provide more info if needed.

**Comment by danngreen** [comment] 2024-11-26 00:21
Sorry, I didn't realize Issues is turned off by default when making a fork. I just added that. @codygeary would you prefer we move the discussion there?

Regarding this patch, it seems to work perfectly until I turn Slew (knob w) all the way to 0 quickly. I can turn Slew down slowly, and there's no problem, but turning it quickly makes the pitch freeze at a high voltage. Once it freezes like that, if I manually adjust the Slew knob down to 0 and then back up, it starts working again. Or if I go to the Module Action menu for the Penta Seq and select "Initialize" then it starts working again. I'm not sure what's happening there.

Another thing is that the manual trigger button (mapped to knob u) is a bit hard to get to trigger using the knob mapping. This seems to need the knob turned all the way to 100% and then to 0% which is a bit hard to do. That's another issue that can be fixed...

With the scope output: can you confirm your scope channel is set to DC, not AC? Because on AC it would behave exactly as you describe, and it's strange you would see a changing voltage but not hear it on the Ouros.

Another idea is that perhaps your Fundamental plugin is not working as expected? If the QNT module were not working then you would indeed get no changing pitch since that would break the connection between the Penta Seq and the Ouros. Could you try removing that module and just patching the Penta Sequencer directly to the Ouros V/Oct input jack? That will help narrow it down.

**Comment by danngreen** [comment] 2024-11-26 04:51
OK, I looked into the code, and I think what's happening is that due to the filtering and calibration of the pots, the MetaModule can send a small negative value for a pot if you turn it quickly. This causes the slew limiters on the Penta Sequencer to lock up.
To confirm, I tried clamping the values on the Penta Sequencer to 0-1. This works great. But -- I think a better long-term fix is to make the MetaModule not send values outside the 0-1 range.

**Comment by codygeary** [comment] 2024-11-26 08:22
Thanks @danngreen !  It's fine if we leave this conversation here.

That's a funny bug, I'm glad you were able to find the source of the problem so quickly!

I'm working on 2.0.11 release, so in that process I'll go through and take a careful look at anything else that ought to be clamped as well- just as good practice.  (And I'll remove that extra debug line in FlowerPatch as well).  When this is all mostly working on MM I'll try to merge the fork back somehow, or I might manually copy paste the files (I'm not super good at git yet), as it would be cool to have it all in the main repo once it flies.

Thanks again for all of your help with this port!

**Comment by rjsmith** [comment] 2024-11-26 18:03
Hi - thanks very much @danngreen . I just re-built and re-tested the latest https://github.com/4ms/CVfunk-Modules main branch, and this time the Penta Sequencer trigger immediately worked - I can see the "step" lights changing on the UI, and the CV outputs now look as expected, tracking the CV step values and slew etc!

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/76dc0cf7-3f10-4129-be85-0e7f8820c3e7">

**Comment by danngreen** [comment] 2024-11-26 22:32
Great! I can see now in the pic above, the little squiggle `~` under the channel name is the AC mode was enabled on channel 2L (green channel) vs. it's disabled on channel 1 (the light blue channel). That explains the weird "return to 0V" thing you saw originally.

**Comment by danngreen** [comment] 2024-11-28 05:06
I merged in a fix to the metamodule main firmware that prevents the pot value from dipping negative. So even without any changes to the CV Funk code, it should work now

**Comment by codygeary** [comment] 2024-11-30 09:15
Awesome! @danngreen 
I'm closing the issue now, as it looks like it's totally solved. :-)

**Closed by codygeary** 2024-11-30 09:15 UTC
